### ISSUE TITLE
Error when relocating moov atom on certain files

### ISSUE THREAD

**Issue by outlyer** [danielgtaylor/qtfaststart#20]
In 99% of test cases, the relocation works fine however, in rare instances the following error is observed. I can't find any consistent criteria about the file to indicate why this is the case, but here is the error produced:

```
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/site-packages/qtfaststart/processor.py", line 197, in process
    moov = _patch_moov(datastream, moov_atom, offset)
  File "/usr/local/lib/python2.7/site-packages/qtfaststart/processor.py", line 263, in _patch_moov
    moov.write(struct.pack(struct_fmt, *offset_entries))
struct.error: 'L' format requires 0 <= number <= 4294967295
```

I can provide some of the file in question if needed.

**Comment by mtrolley** [comment]
I'm having this error as well.
